# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: python get_config.py
  displayName: 'Run a one-line script'

- script: kubectl apply -f was-job-updated.yaml
  displayName: 'Run a one-line script'


